# Use an official base image
FROM docker.elastic.co/elasticsearch/elasticsearch:7.14.0

# Set environment variables
ENV discovery.type single-node

# Expose Elasticsearch ports
EXPOSE 9200 9300

# Run Elasticsearch
CMD ["-E", "network.host=0.0.0.0", "-E", "discovery.type=single-node"]
